---
- hosts: all
  become: yes
  tasks:
  - name: install fail2ban
    apt:
      name:
        - fail2ban
      update_cache: yes
  - name: copy fail2ban config
    copy:
      src: config/sshd-default.conf
      dest: /etc/fail2ban/jail.d/sshd-default.conf
  - name: restart fail2ban
    systemd:
      state: restarted
      daemon_reload: yes
      name: fail2ban